In [3]:
import numpy as np
# creating array
arr=np.array([1,2,3,4,5], dtype=float)
print(arr)

[1. 2. 3. 4. 5.]


In [4]:
zeros_arr=np.zeros((3,3), dtype=float)
print(zeros_arr)
ones_arr=np.ones((2,2), dtype=int)
print(ones_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1]
 [1 1]]


In [6]:
arange_arr=np.arange(10)
print(arange_arr)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
# array manipulation
arr=np.array([1,2,3,4,5])
reshaped_arr=arr.reshape(5,1)
print(reshaped_arr)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [9]:
# slicing
sliced_arr=arr[2:4]
print(sliced_arr)

[3 4]


In [11]:
# transpose
a=np.array([1,2,3,4,5,6,7,8])
b=a.T
print(b)

[1 2 3 4 5 6 7 8]


In [12]:
#split
b=np.split(a,4)
print(b)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [13]:
# matrix multiplication
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)

[[19 22]
 [43 50]]


In [14]:
d=np.linalg.eig(c)
print(d)

EigResult(eigenvalues=array([5.80198014e-02, 6.89419802e+01]), eigenvectors=array([[-0.75781077, -0.40313049],
       [ 0.65247439, -0.91514251]]))


In [21]:
# loading and saving
import numpy as np
data=np.loadtxt("/content/drive/MyDrive/dataset/DAP SAMPLE.txt",dtype=int)
d=np.savetxt("/content/DAPP SAMPLE.txt", data)
print(d)
print(data)

None
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [26]:
arange_arr=np.arange(0,100,5)
print(arange_arr)
c=np.savetxt("/content/ash.txt",arange_arr)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [32]:
a=np.random.rand()
print(a)
b=np.random.randint(10,20)
print(b)

0.40902223899360846
19


In [38]:
a=np.array([[1,2] ,[3,4]])
print(a.ndim)
print(type(a))

2
<class 'numpy.ndarray'>


In [40]:
a=np.linspace(0.8,2,5)
print(a)

[0.8 1.1 1.4 1.7 2. ]


In [44]:
arange_arr=np.arange(24).reshape(3,2,4)
print(arange_arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [50]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])
print(a*b)
print(a@b)
print(np.dot(a,b))



[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]


In [56]:
from numpy import random
a=np.ones((2,3),dtype=int)
print(a)
print(a.sum())
print(a.sum(axis=0))

[[1 1 1]
 [1 1 1]]
6
[2 2 2]


In [68]:
a=np.ceil((np.random.rand(2,12)))
print(a)
b=np.random.random((2,12))
print(b)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0.9773539  0.28654651 0.54994125 0.29492418 0.40328175 0.12847052
  0.73422051 0.27404743 0.69638883 0.10597929 0.59286617 0.22147565]
 [0.92761246 0.64888307 0.53659898 0.01472972 0.66175711 0.48629975
  0.75718765 0.29043655 0.97573785 0.2311096  0.43923322 0.2801853 ]]


In [71]:
a=np.ones((2,3),dtype=int)
print(a)
print(a.max())
print(a.max(axis=1))

[[1 1 1]
 [1 1 1]]
1
[1 1]


In [76]:
a=np.array((3,3),dtype=int)
print(a.min())
print(a.min(axis=0))

3
3


In [84]:
a=np.array([2,3,5,6,7,8])
a.resize(3,2)
print(a)
print(a.shape)
a.cumsum()

[[2 3]
 [5 6]
 [7 8]]
(3, 2)


array([ 2,  5, 10, 16, 23, 31])

In [86]:
a=np.array([1,2,3,4,5,6])
a.resize(2,3)
b=np.array([2,3,4,5,6,7])
b.resize(2,3)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [4 5 6]
 [2 3 4]
 [5 6 7]]
[[1 2 3 2 3 4]
 [4 5 6 5 6 7]]


In [93]:
a=np.arange(30).reshape(3,2,5)
print(a)
print(np.dstack(a))


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]
[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]
  [ 3 13 23]
  [ 4 14 24]]

 [[ 5 15 25]
  [ 6 16 26]
  [ 7 17 27]
  [ 8 18 28]
  [ 9 19 29]]]


In [3]:
import numpy as np
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
a=np.full((2,2),3)
print(a)
print(a.itemsize)

[[3 3]
 [3 3]]
8


In [5]:
x=[1,2,3]
a=np.asarray(x)
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [6]:
x=np.array([1,4,0],float)
y=np.array([2,2,1],float)
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))

10.0
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
[ 4. -1. -6.]


In [8]:
a=np.array([1.3,4.1,5.2,3.4,2.5,1.1,2.2])
print(np.rint(a))


[1. 4. 5. 3. 2. 1. 2.]


In [9]:
a=np.array([1,2,3,4,5])
b=np.array([2,3,4,5,6])
print(np.true_divide(a,b))

[0.5        0.66666667 0.75       0.8        0.83333333]


In [11]:
a=np.array([1,1,2,2,3,3,4,4])
print(np.unique(a))

[1 2 3 4]


In [13]:
a=np.array([[1,2,3],[1,2,3]])
b=np.array([[2,3,4],[2,3,4]])
print(np.union1d(a,b))

[1 2 3 4]


In [14]:
a=np.array([[1,2,3],[1,2,3]])
b=np.array([[2,3,4],[2,3,4]])
print(np.intersect1d(a,b))

[2 3]


In [15]:
a=np.array([[1,2,3],[1,2,3]])
b=np.array([[2,3,4],[2,3,4]])
print(np.setdiff1d(a,b))

[1]


In [16]:
a=8
b=6
c=np.hypot(a,b)
print(c)

10.0


In [17]:
x=np.sin(0)
print(x)

0.0


In [18]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.divmod(a,b)
print(c)

(array([ 0,  1, 15,  2,  2,  2]), array([10,  0,  0,  0,  0, 10]))


In [19]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.divide(a,b)
print(c)

[ 0.5  1.  15.   2.   2.   2.4]


In [20]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.multiply(a,b)
print(c)

[ 200  441   60  800 1250 1500]


In [24]:
from numpy import random
x=random.normal(size=(2,3))
print(x)

[[-0.39627095  0.00808826  0.58418241]
 [-0.89589339  2.2581893  -0.10010361]]


In [25]:
from numpy import random
x=random.normal(loc=1,scale=2,size=(2,3))
print(x)

[[ 0.78046486 -1.127157   -0.46668268]
 [ 0.5952946  -0.59850297  2.92265204]]


In [26]:
x=random.binomial(n=12,p=0.5,size=10)
print(x)

[7 7 7 6 7 5 7 4 6 9]


In [27]:
x=random.poisson(lam=2,size=10)
print(x)

[4 3 0 3 4 1 4 1 3 1]


In [29]:
x=random.choice([1,2,3])
print(x)

3


In [32]:
x=random.choice([3,5],p=[0.5,0.5],size=(3,5))
print(x)

[[5 5 3 5 3]
 [3 3 5 3 3]
 [5 5 5 5 3]]
